# Importing data

Ref: https://campus.datacamp.com/courses/importing-data-in-python-part-1

Dr. Sandeep Nagar

The notebook will cover data import from:
* Files with formats like txt, csv etc.
* Files from softwares like MS Excel
* Files from relational databases

## Textfiles

There are two kinds of textfiles:

* Simple text files containing Unicode of ASCII characters (ex. txt)
* Tables identifying a data point by a row and column index (ex. csv)

### .txt files

* First a file is opened using `open()` function, then some action is perfomed and then the file is closed using `close()` function.
* File is opened in a mode i.e `r` for read, `w` write etc.

Lets take an example. Lets first downlaod the a text file from https://www.gutenberg.org/ebooks/32325 and save in the same folder as this notebook. The filename os this file is `huck.txt`. The file is encoded in UTF-8.

Filenames are to be fed as strings. Lets store this string in a variable named `filename`

In [1]:
filename = "huck.txt"

Now `open()` function takes two arguments:

* filename
* mode

Here we will feed the variable strong the file name as first input and read mode (signified by string `r`) as second argument

In [2]:
file = open(filename,mode='r')

Lets check which kind of object is referred by `file`

In [3]:
file

<_io.TextIOWrapper name='huck.txt' mode='r' encoding='UTF-8'>

It is an input-output object where name, mode and encoding is identified correctly.

Now lets read the file and store the content in a variable named `text` and inspect the same. It is worth noting that one must close the connection to the file as soon as its read and stored in a variable

In [4]:
text = file.read()
file.close()

Now lets print the contents of the file to our screen

In [5]:
print(text)

Project Gutenberg's The Adventures of Huckleberry Finn, by Mark Twain

This eBook is for the use of anyone anywhere at no cost and with
almost no restrictions whatsoever.  You may copy it, give it away or
re-use it under the terms of the Project Gutenberg License included
with this eBook or online at www.gutenberg.org


Title: The Adventures of Huckleberry Finn
       Tom Sawyer's Comrade

Author: Mark Twain

Release Date: May 10, 2010 [EBook #32325]

Language: English


*** START OF THIS PROJECT GUTENBERG EBOOK THE ADVENTURES OF HUCKLEBERRY FINN ***




Produced by James Adcock. Special thanks to The Internet
Archive: American Libraries.






[Illustration: Photo of the Author with Signature "S. L. Clemens"]

THE ADVENTURES

OF

HUCKLEBERRY FINN

(TOM SAWYER'S COMRADE)



   SCENE: The Mississippi Valley
   TIME: Forty to Fifty Years Ago



   By Mark Twain



   ILLUSTRATED



   _NEW EDITION FROM NEW PLATES_




   HARPER & BROTHERS PUBLISHERS

   NEW YORK AND LONDON



Books by M

Note that the whole book is stored in memory and this memory location is referenced by the variable name `text`

The whole excercise can be done within a single statemnet block using `with` structure:

In [6]:
with open(filename,mode='r') as file:
    print(file.read())

Project Gutenberg's The Adventures of Huckleberry Finn, by Mark Twain

This eBook is for the use of anyone anywhere at no cost and with
almost no restrictions whatsoever.  You may copy it, give it away or
re-use it under the terms of the Project Gutenberg License included
with this eBook or online at www.gutenberg.org


Title: The Adventures of Huckleberry Finn
       Tom Sawyer's Comrade

Author: Mark Twain

Release Date: May 10, 2010 [EBook #32325]

Language: English


*** START OF THIS PROJECT GUTENBERG EBOOK THE ADVENTURES OF HUCKLEBERRY FINN ***




Produced by James Adcock. Special thanks to The Internet
Archive: American Libraries.






[Illustration: Photo of the Author with Signature "S. L. Clemens"]

THE ADVENTURES

OF

HUCKLEBERRY FINN

(TOM SAWYER'S COMRADE)



   SCENE: The Mississippi Valley
   TIME: Forty to Fifty Years Ago



   By Mark Twain



   ILLUSTRATED



   _NEW EDITION FROM NEW PLATES_




   HARPER & BROTHERS PUBLISHERS

   NEW YORK AND LONDON



Books by M

For large files, we may not want to print all of their content to the shell: you may wish to print only the first few lines. Here the `readline()` method comes handy.

In [7]:
with open(filename,mode='r') as file:
    print(file.readline())

Project Gutenberg's The Adventures of Huckleberry Finn, by Mark Twain



Each time, `readline()` method is called on a file object, it read a line. If it is called succesively, it reads next line each time.

In [8]:
with open(filename,mode='r') as file:
    print(file.readline())
    print(file.readline())
    print(file.readline())
    print(file.readline())

Project Gutenberg's The Adventures of Huckleberry Finn, by Mark Twain



This eBook is for the use of anyone anywhere at no cost and with

almost no restrictions whatsoever.  You may copy it, give it away or



Suppose we wish to read first nine lines, then we can use a `for` loop as follows:

In [9]:
with open(filename,mode='r') as file:
    for i in range(20):
        print(file.readline())

Project Gutenberg's The Adventures of Huckleberry Finn, by Mark Twain



This eBook is for the use of anyone anywhere at no cost and with

almost no restrictions whatsoever.  You may copy it, give it away or

re-use it under the terms of the Project Gutenberg License included

with this eBook or online at www.gutenberg.org





Title: The Adventures of Huckleberry Finn

       Tom Sawyer's Comrade



Author: Mark Twain



Release Date: May 10, 2010 [EBook #32325]



Language: English





*** START OF THIS PROJECT GUTENBERG EBOOK THE ADVENTURES OF HUCKLEBERRY FINN ***





### .csv files

You can see a `.csv` (comma seperated values) file named as `marks.csv` in the same folder as this notebook

In [10]:
ls

Importing data - 1.ipynb  huck.txt                  marks.csv


We shall use this file henceforth. This file contains marks of 15 students in a class for physics and chemistry as well as total marks.

These kind of files are also called `fat files` as they contained basic text data but in a tabular format but the file does not store the relationship between data entries. 
* The data is just seperated by delimiters. In a `csv` file, the delimiter for each element entry is a comma and delimiter seperating rows is a newline character `\n`
* The file has a `header` having information about labels of columns

They can be stored as variety of python objects as per requirements. Mostly, they are stored as either `numpy arrays` or `pandas dataframes`. Lets first start with `numpy arrays`

In [11]:
import numpy as np

In [12]:
filename = 'marks.csv'

Now we shall use `numpy.loadtext()` function where we have to feed the `filename`, `delimiter=","` and `skiprows=1` because first row contains strings as header.

In [13]:
data = np.loadtxt(filename, delimiter=",", skiprows=1)

In [14]:
data

array([[  1.,   7.,   3.,  10.],
       [  2.,   6.,   9.,  15.],
       [  3.,   8.,   8.,  16.],
       [  4.,   4.,   6.,  10.],
       [  5.,   8.,   8.,  16.],
       [  6.,   3.,   4.,   7.],
       [  7.,   5.,   7.,  12.],
       [  8.,   6.,   4.,  10.],
       [  9.,   7.,   8.,  15.],
       [ 10.,   2.,   5.,   7.],
       [ 11.,   4.,   2.,   6.],
       [ 12.,   9.,   5.,  14.],
       [ 13.,   3.,   8.,  11.],
       [ 14.,   6.,   3.,   9.],
       [ 15.,   9.,   6.,  15.]])

Lets probe some features of this newly created array referenced by variable name `data`

In [15]:
np.ndim(data) # number of dimesnions

2

In [16]:
np.size(data) # Total number of elements 

60

In [17]:
np.shape(data) # Total number of rows and columns

(15, 4)

If we wish to use only the second and third column of file we can use `usecols` arguments supplied with a list `[1,2]`

In [18]:
data1 = np.loadtxt(filename, delimiter=",", skiprows=1, usecols=[1,2])

In [19]:
data1

array([[ 7.,  3.],
       [ 6.,  9.],
       [ 8.,  8.],
       [ 4.,  6.],
       [ 8.,  8.],
       [ 3.,  4.],
       [ 5.,  7.],
       [ 6.,  4.],
       [ 7.,  8.],
       [ 2.,  5.],
       [ 4.,  2.],
       [ 9.,  5.],
       [ 3.,  8.],
       [ 6.,  3.],
       [ 9.,  6.]])

The header contains strings and suppose we wish to use them too then we can define additional data types to be entertained while importing using `dtype=str` argument.

In [20]:
data1 = np.loadtxt(filename, delimiter=",", usecols=[1,2],dtype=str)

In [21]:
data1

array([["b'Physics'", "b'Chemisry'"],
       ["b'7'", "b'3'"],
       ["b'6'", "b'9'"],
       ["b'8'", "b'8'"],
       ["b'4'", "b'6'"],
       ["b'8'", "b'8'"],
       ["b'3'", "b'4'"],
       ["b'5'", "b'7'"],
       ["b'6'", "b'4'"],
       ["b'7'", "b'8'"],
       ["b'2'", "b'5'"],
       ["b'4'", "b'2'"],
       ["b'9'", "b'5'"],
       ["b'3'", "b'8'"],
       ["b'6'", "b'3'"],
       ["b'9'", "b'6'"]], 
      dtype='<U11')

When we have mixed data types for input data then instead of `numpy arrays` we should use `pandas dataframes`.

But `numpy` also has another function named `genfromtxt` which can handle mixed data types to some success.

In [22]:
data2 = np.genfromtxt(filename, delimiter=',')

In [23]:
data2

array([[ nan,  nan,  nan,  nan],
       [  1.,   7.,   3.,  10.],
       [  2.,   6.,   9.,  15.],
       [  3.,   8.,   8.,  16.],
       [  4.,   4.,   6.,  10.],
       [  5.,   8.,   8.,  16.],
       [  6.,   3.,   4.,   7.],
       [  7.,   5.,   7.,  12.],
       [  8.,   6.,   4.,  10.],
       [  9.,   7.,   8.,  15.],
       [ 10.,   2.,   5.,   7.],
       [ 11.,   4.,   2.,   6.],
       [ 12.,   9.,   5.,  14.],
       [ 13.,   3.,   8.,  11.],
       [ 14.,   6.,   3.,   9.],
       [ 15.,   9.,   6.,  15.]])

In [24]:
np.ndim(data2) # number of dimesnions

2

Clearly it just substituted `nan` to all non-numerical data type values. If we supply the argument `dtype=None` it will figure out what types each column should be.

In [25]:
data3 = np.genfromtxt(filename, delimiter=',',dtype=None)

In [26]:
data3

array([[b'Roll Number', b'Physics', b'Chemisry', b'Total'],
       [b'1', b'7', b'3', b'10'],
       [b'2', b'6', b'9', b'15'],
       [b'3', b'8', b'8', b'16'],
       [b'4', b'4', b'6', b'10'],
       [b'5', b'8', b'8', b'16'],
       [b'6', b'3', b'4', b'7'],
       [b'7', b'5', b'7', b'12'],
       [b'8', b'6', b'4', b'10'],
       [b'9', b'7', b'8', b'15'],
       [b'10', b'2', b'5', b'7'],
       [b'11', b'4', b'2', b'6'],
       [b'12', b'9', b'5', b'14'],
       [b'13', b'3', b'8', b'11'],
       [b'14', b'6', b'3', b'9'],
       [b'15', b'9', b'6', b'15']], 
      dtype='|S11')

In [27]:
np.ndim(data3)

2

To define explicity that there is a header, one should uses `names=True` argument

In [28]:
data4 = np.genfromtxt(filename, delimiter=',', names=True, dtype=None)

In [29]:
data4

array([( 1, 7, 3, 10), ( 2, 6, 9, 15), ( 3, 8, 8, 16), ( 4, 4, 6, 10),
       ( 5, 8, 8, 16), ( 6, 3, 4,  7), ( 7, 5, 7, 12), ( 8, 6, 4, 10),
       ( 9, 7, 8, 15), (10, 2, 5,  7), (11, 4, 2,  6), (12, 9, 5, 14),
       (13, 3, 8, 11), (14, 6, 3,  9), (15, 9, 6, 15)], 
      dtype=[('Roll_Number', '<i8'), ('Physics', '<i8'), ('Chemisry', '<i8'), ('Total', '<i8')])

In [30]:
np.ndim(data4)

1

Its worth noting that number of dimesnions in above case isn't 2 but 1. Why?

* Because all the element of a numpy array must be of same `type` hence the function `genfromtxt` makes entires of similar data type

Accessing a colum is now simply passing the row name as index

In [32]:
data4["Roll_Number"]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [33]:
data4["Physics"]

array([7, 6, 8, 4, 8, 3, 5, 6, 7, 2, 4, 9, 3, 6, 9])

In [36]:
data4["Total"]

array([10, 15, 16, 10, 16,  7, 12, 10, 15,  7,  6, 14, 11,  9, 15])

Another function named `recfromcsv()` exists where default `dtype=None` i.e it will input all data types without any issues and default delimiter is a comma, so they need not be explicitly mentioned.

In [37]:
data5 = np.recfromcsv(filename)

In [38]:
data5

rec.array([( 1, 7, 3, 10), ( 2, 6, 9, 15), ( 3, 8, 8, 16), ( 4, 4, 6, 10),
 ( 5, 8, 8, 16), ( 6, 3, 4,  7), ( 7, 5, 7, 12), ( 8, 6, 4, 10),
 ( 9, 7, 8, 15), (10, 2, 5,  7), (11, 4, 2,  6), (12, 9, 5, 14),
 (13, 3, 8, 11), (14, 6, 3,  9), (15, 9, 6, 15)], 
          dtype=[('roll_number', '<i8'), ('physics', '<i8'), ('chemisry', '<i8'), ('total', '<i8')])

Note that the characters of headers have been formatted where capital letters have been changed into small letter

In [44]:
data5.ndim

1

In [45]:
type(data5)

numpy.recarray

The array created from `recfromcsv` is to the type `recarray` which is an ndarray which allows the fiel daccess using attributes. 

In [41]:
help(np.recarray)

Help on class recarray in module numpy:

class recarray(ndarray)
 |  Construct an ndarray that allows field access using attributes.
 |  
 |  Arrays may have a data-types containing fields, analogous
 |  to columns in a spread sheet.  An example is ``[(x, int), (y, float)]``,
 |  where each entry in the array is a pair of ``(int, float)``.  Normally,
 |  these attributes are accessed using dictionary lookups such as ``arr['x']``
 |  and ``arr['y']``.  Record arrays allow the fields to be accessed as members
 |  of the array, using ``arr.x`` and ``arr.y``.
 |  
 |  Parameters
 |  ----------
 |  shape : tuple
 |      Shape of output array.
 |  dtype : data-type, optional
 |      The desired data-type.  By default, the data-type is determined
 |      from `formats`, `names`, `titles`, `aligned` and `byteorder`.
 |  formats : list of data-types, optional
 |      A list containing the data-types for the different columns, e.g.
 |      ``['i4', 'f8', 'i4']``.  `formats` does *not* support th

In [43]:
data5["total"]

array([10, 15, 16, 10, 16,  7, 12, 10, 15,  7,  6, 14, 11,  9, 15])

Although arrays provides good options to deal with data in files, they still lack the basic need of data science i.e different data types in different rows and columns. Hence `pandas.dataframes` becomes a good choice for the same.

Reading a `.csv` file can be done using `read_csv()` function of pandas as follows:

In [47]:
import pandas as pd

In [48]:
data6 = pd.read_csv(filename)

In [49]:
data6

Roll Number  Physics  Chemisry  Total
0             1        7         3     10
1             2        6         9     15
2             3        8         8     16
3             4        4         6     10
4             5        8         8     16
5             6        3         4      7
6             7        5         7     12
7             8        6         4     10
8             9        7         8     15
9            10        2         5      7
10           11        4         2      6
11           12        9         5     14
12           13        3         8     11
13           14        6         3      9
14           15        9         6     15

Wow, this looks really cool. Its looks so similar to opening an excel file.

In [54]:
type(data6)

pandas.core.frame.DataFrame

When we have bigger files, we can check the HEAD and TAIL of dataframe using `head()` and `tail()` methods which lists the first five entries of rows and columns

In [50]:
data6.head()

Roll Number  Physics  Chemisry  Total
0            1        7         3     10
1            2        6         9     15
2            3        8         8     16
3            4        4         6     10
4            5        8         8     16

In [51]:
data6.tail()

Roll Number  Physics  Chemisry  Total
10           11        4         2      6
11           12        9         5     14
12           13        3         8     11
13           14        6         3      9
14           15        9         6     15

A dataframe can be converted to a numpy array by calling the `values` method

In [55]:
data6_array = data6.values

In [56]:
data6_array

array([[ 1,  7,  3, 10],
       [ 2,  6,  9, 15],
       [ 3,  8,  8, 16],
       [ 4,  4,  6, 10],
       [ 5,  8,  8, 16],
       [ 6,  3,  4,  7],
       [ 7,  5,  7, 12],
       [ 8,  6,  4, 10],
       [ 9,  7,  8, 15],
       [10,  2,  5,  7],
       [11,  4,  2,  6],
       [12,  9,  5, 14],
       [13,  3,  8, 11],
       [14,  6,  3,  9],
       [15,  9,  6, 15]])

In [57]:
type(data6_array)

numpy.ndarray

Pandas module is also good at dealing wth some important issues:

* Dealing with NaN values as entries of data
* Dealing with NA values as entries of data
* comments

The arguments:

* `sep` defines the delimitor string
* `comment` defines the chracter which defines a comment till end-of-line character is encountered
* na_values can take valyes `"NaN"`, `"NA"` and `"Nothing"`